project:
  type: website

website:
  title: "Drew Dimmery"
  description: "Personal website of Drew Dimmery"
  site-url: https://ddimmery.com
  repo-url: https://github.com/ddimmery/quarto-website
  google-analytics: "G-Y7YLFF5F90"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@drewdim"
    site: "@drewdim"
    image-width: 1200
    image-height: 600
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: software.qmd
      - href: blog.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html

