project:
  type: default
  output-dir: ./paper/

manuscript:
  article: Mitchell2024_JASA-SPI.qmd
  notebooks:
    - ./notebooks/SingleIndex-Code.ipynb
    - ./notebooks/TargetOptimization.ipynb

bibliography: FellowshipRefs2.bib

format:
  html:
    clean: true
    toc: true
    code-fold: true
    embed-resources: true
    self-contained-math: true
    # output-file: paper.html
    comments:
      hypothesis: true
  # docx: default
  # jats: default
  # typst: default
  elsevier-pdf:
    latex-clean: true
    # latex-output-dir: _tex
    keep-tex: false
    # output-file: paper.pdf
    hyperrefoptions: 
      - "citecolor=black"
    echo: false
    journal:
      name: Journal of the Acoustical Society of America
      model: 3p
      cite-style: authoryear
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          % Note: setting commandchars=\\\{\} here will cause an error 
          }

  # (other formats)
  # pdf: default

execute:
  freeze: auto
  keep-ipynb: false