project:
  type: default
  output-dir: ./paper/

manuscript:
  article: index.qmd
  notebooks:
    - ./notebooks/SingleIndex-Code.ipynb
    - ./notebooks/TargetOptimization.ipynb

bibliography: FellowshipRefs-biblatex.bib

format:
  html:
    # clean: true
    toc: true
    code-fold: true
    # embed-resources: true
    self-contained-math: true
    # output-file: paper.html
    comments:
      hypothesis: true
  # docx: default
  # jats: default
  # typst: default
  elsevier-pdf:
    # latex-clean: true
    # latex-output-dir: _tex
    keep-tex: false
    # output-file: paper.pdf
    hyperrefoptions: 
      - "citecolor=black"
    echo: false
    journal:
      name: Journal of the Acoustical Society of America
      formatting: preprint
      model: 3p
      cite-style: authoryear

  # (other formats)
  # pdf: default

execute:
  freeze: auto
  keep-ipynb: true